### ISSUE TITLE
Improved reliability when snapshot is a function

### ISSUE THREAD

**Issue by zubairov** [elasticio/elasticio-cli#3]
In my component I do

```
this.emit('snapshot', function() {})
```

Causes exception

```

/Users/zubairov/Repositories/components/node_modules/q/q.js:126
                    throw e;
                          ^
TypeError: Cannot read property 'info' of undefined
    at onSnapshot (/Users/zubairov/.nvm/v0.10.22/lib/node_modules/elasticio-cli/lib/process.js:65:54)
    at EventEmitter.emit (events.js:95:17)
    at /Users/zubairov/Repositories/components/lib/components/gspreadsheets/triggers/rows.js:189:14
    at Promise.apply (/Users/zubairov/Repositories/components/node_modules/q/q.js:1120:26)
    at Promise.promise.promiseDispatch (/Users/zubairov/Repositories/components/node_modules/q/q.js:751:41)
    at /Users/zubairov/Repositories/components/node_modules/q/q.js:1335:14
    at flush (/Users/zubairov/Repositories/components/node_modules/q/q.js:108:17)
    at process._tickDomainCallback (node.js:459:13)
```

**Comment by hannah-bulmer** [comment]
Resolved in updated version of component
