### ISSUE TITLE
Script elasticio does not work

### ISSUE THREAD

**Issue by zubairov** [elasticio/elasticio-cli#55]
Unfortunately can't start `elasticio` after installation on node.12

```zubairov@Renats-MacBook ~> nvm use 12
Now using node v12.18.1 (npm v6.14.5)
zubairov@Renats-MacBook ~> npm install elasticio-cli -g
/Users/zubairov/.nvm/versions/node/v12.18.1/bin/elasticio -> /Users/zubairov/.nvm/versions/node/v12.18.1/lib/node_modules/elasticio-cli/elasticio

> spawn-sync@1.0.15 postinstall /Users/zubairov/.nvm/versions/node/v12.18.1/lib/node_modules/elasticio-cli/node_modules/spawn-sync
> node postinstall


> elasticio-cli@2.1.0 postinstall /Users/zubairov/.nvm/versions/node/v12.18.1/lib/node_modules/elasticio-cli
> echo 'Object.assign(exports, require("./packages/inquirer/lib/inquirer"));' > node_modules/inquirer/index.js

+ elasticio-cli@2.1.0
added 101 packages from 86 contributors in 5.37s
zubairov@Renats-MacBook ~> elasticio
internal/modules/cjs/loader.js:969
  throw err;
  ^

Error: Cannot find module 'rxjs'
Require stack:
- /Users/zubairov/.nvm/versions/node/v12.18.1/lib/node_modules/elasticio-cli/node_modules/inquirer/packages/inquirer/lib/ui/prompt.js
- /Users/zubairov/.nvm/versions/node/v12.18.1/lib/node_modules/elasticio-cli/node_modules/inquirer/packages/inquirer/lib/inquirer.js
- /Users/zubairov/.nvm/versions/node/v12.18.1/lib/node_modules/elasticio-cli/node_modules/inquirer/index.js
- /Users/zubairov/.nvm/versions/node/v12.18.1/lib/node_modules/elasticio-cli/lib/helpers/prompts.js
- /Users/zubairov/.nvm/versions/node/v12.18.1/lib/node_modules/elasticio-cli/lib/executables/process.js
- /Users/zubairov/.nvm/versions/node/v12.18.1/lib/node_modules/elasticio-cli/elasticio
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
    at Function.Module._load (internal/modules/cjs/loader.js:842:27)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/zubairov/.nvm/versions/node/v12.18.1/lib/node_modules/elasticio-cli/node_modules/inquirer/packages/inquirer/lib/ui/prompt.js:3:34)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/zubairov/.nvm/versions/node/v12.18.1/lib/node_modules/elasticio-cli/node_modules/inquirer/packages/inquirer/lib/inquirer.js:19:11)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/zubairov/.nvm/versions/node/v12.18.1/lib/node_modules/elasticio-cli/node_modules/inquirer/packages/inquirer/lib/ui/prompt.js',
    '/Users/zubairov/.nvm/versions/node/v12.18.1/lib/node_modules/elasticio-cli/node_modules/inquirer/packages/inquirer/lib/inquirer.js',
    '/Users/zubairov/.nvm/versions/node/v12.18.1/lib/node_modules/elasticio-cli/node_modules/inquirer/index.js',
    '/Users/zubairov/.nvm/versions/node/v12.18.1/lib/node_modules/elasticio-cli/lib/helpers/prompts.js',
    '/Users/zubairov/.nvm/versions/node/v12.18.1/lib/node_modules/elasticio-cli/lib/executables/process.js',
    '/Users/zubairov/.nvm/versions/node/v12.18.1/lib/node_modules/elasticio-cli/elasticio'
  ]
}
```

**Comment by zubairov** [comment]
Apparently after manual installation of `rxjs` script start working:

```
npm install rxjs -g
```

**Comment by jhorbulyk** [comment]
I did not encounter this problem with a fresh install on my windows VM:
![Screenshot from 2020-06-29 10-18-40](https://user-images.githubusercontent.com/5710732/85990215-fa8ca680-b9f1-11ea-9388-a8a1f75a8fd7.png)

**Comment by zubairov** [comment]
did you tried to delete the NPM global cache on the disk?

**Comment by jhorbulyk** [comment]
> did you tried to delete the NPM global cache on the disk?

What do you mean by this?
